### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by firelilith** [thatGuySpectre/Kanka-API-Client#7]
# Needs to be done
- [ ] improve caching with LastSync: https://kanka.io/en/docs/1.0/last-sync
- [ ] create subentries for:
  - [ ] maps
  - [ ] location map points
  - [ ] organisation members
  - [ ] quests
  - [ ] timelines
  - [ ] calendars ? (fairly broken at the moment)
- [ ] get user profiles
- [ ] implement menu links: https://kanka.io/en/docs/1.0/menu-links
- [ ] implement dashboard widgets: https://kanka.io/en/docs/1.0/dashboard-widgets
- [ ] implement templates: https://kanka.io/en/docs/1.0/templates
- [x] allow different mention locales: https://kanka.io/en/docs/1.0/mention-language
- [x] a lot of entity stuff:
  - [x] Attributes
  - [x] Entity Events
  - [x] Entity Files - currently broken
  - [x] Entity Inventory
  - [x] Entity Mentions
  - [x] Entity Notes
  - [x] Entity Tags
  - [x] Relations
  - [x] Inventory
  - [x] Entity Abilities
  - [x] Entity Links
  - [x] Entity Image - not needed
- [x] implement image uploads to entities
